import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { formatPercent, formatTimestamp } from '../utils/formatters';
export const DiagnosticPanel = ({ diagnosis }) => {
    if (!diagnosis) {
        return (_jsxs("div", { "data-testid": "diagnostic-panel", className: "border border-zinc-300 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm p-6 text-center", children: [_jsx("div", { className: "w-12 h-12 rounded-full bg-zinc-100 dark:bg-zinc-800 flex items-center justify-center mx-auto mb-3", children: _jsx("svg", { className: "w-6 h-6 text-zinc-400", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 1.5, d: "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" }) }) }), _jsx("h3", { className: "font-mono text-sm font-bold text-zinc-800 dark:text-zinc-200", children: "No Diagnostic Assessment Available" }), _jsx("p", { className: "font-sans text-xs text-zinc-500 mt-1 max-w-md mx-auto", children: "The autonomous AI diagnostic reasoner runs when multivariate anomalies are detected. Currently all operating telemetry is within nominal tolerances." })] }));
    }
    const getSeverityBadge = () => {
        switch (diagnosis.severity) {
            case 'critical':
                return 'bg-red-500/20 text-red-400 border-red-500/40 animate-pulse';
            case 'warning':
                return 'bg-amber-500/20 text-amber-300 border-amber-500/40';
            case 'info':
            default:
                return 'bg-blue-500/20 text-blue-300 border-blue-500/40';
        }
    };
    return (_jsxs("div", { "data-testid": "diagnostic-panel", className: "border border-zinc-300 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm overflow-hidden", children: [_jsxs("div", { className: "p-4 border-b border-zinc-200 dark:border-zinc-800 bg-zinc-50/70 dark:bg-zinc-950/60 flex flex-wrap items-center justify-between gap-3", children: [_jsxs("div", { className: "flex items-center gap-2.5", children: [_jsx("span", { className: "w-2.5 h-2.5 rounded-full bg-blue-600 animate-ping" }), _jsx("h2", { className: "font-mono text-sm font-bold text-zinc-900 dark:text-zinc-100 uppercase tracking-wide", children: "CURRENT DIAGNOSTIC ASSESSMENT" }), _jsx("span", { className: `px-2 py-0.5 text-[10px] font-mono font-bold uppercase rounded border ${getSeverityBadge()}`, children: diagnosis.severity }), diagnosis.stage && (_jsxs("span", { className: "px-2 py-0.5 text-[10px] font-mono bg-zinc-200 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300 border border-zinc-300 dark:border-zinc-700 rounded uppercase", children: [diagnosis.stage, " STAGE"] }))] }), _jsxs("div", { className: "font-mono text-xs text-zinc-500 flex items-center gap-3", children: [diagnosis.timestamp && (_jsxs("span", { children: ["Timestamp: ", formatTimestamp(diagnosis.timestamp)] })), diagnosis.confidence !== null && (_jsxs("span", { children: ["Confidence: ", _jsx("strong", { className: "text-zinc-900 dark:text-zinc-100", children: formatPercent(diagnosis.confidence) })] }))] })] }), _jsxs("div", { className: "p-5 space-y-5", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [_jsxs("div", { className: "md:col-span-2 border border-zinc-200 dark:border-zinc-800 p-4 bg-zinc-50/40 dark:bg-zinc-950/30", children: [_jsx("div", { className: "text-[10px] font-mono font-bold text-zinc-500 uppercase tracking-wider mb-1", children: "Diagnostic Conclusion" }), _jsx("div", { className: "text-base font-mono font-bold text-zinc-900 dark:text-zinc-100 leading-snug", children: diagnosis.diagnosis || 'Diagnostic assessment in progress' })] }), _jsxs("div", { className: "border border-zinc-200 dark:border-zinc-800 p-4 bg-zinc-50/40 dark:bg-zinc-950/30", children: [_jsx("div", { className: "text-[10px] font-mono font-bold text-zinc-500 uppercase tracking-wider mb-1", children: "Suspected Component" }), _jsx("div", { className: "text-lg font-mono font-extrabold text-blue-600 dark:text-blue-400 uppercase", children: (() => {
                                            const comp = diagnosis.suspected_component;
                                            if (!comp)
                                                return 'Component not identified';
                                            if (typeof comp === 'object') {
                                                return comp.display_name || comp.component_id || 'Component not identified';
                                            }
                                            return comp;
                                        })() }), _jsx("div", { className: "text-[10px] font-mono text-zinc-500 mt-1", children: diagnosis.suspected_component ? 'Isolated by multi-signal correlation' : 'No hardware isolate' })] })] }), _jsxs("div", { className: "border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900/60 p-4", children: [_jsxs("div", { className: "font-mono text-xs font-bold text-zinc-800 dark:text-zinc-200 uppercase mb-3 flex items-center gap-2", children: [_jsx("span", { children: "Explainability & Diagnostic Evidence Trail" }), _jsx("span", { className: "text-[10px] font-normal text-zinc-500 font-mono", children: "[OBSERVATIONS \u2192 EVIDENCE \u2192 REASONING]" })] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { children: [_jsxs("div", { className: "text-[11px] font-mono font-semibold text-zinc-500 mb-1", children: ["EVIDENCE USED (", diagnosis.evidence_used?.length || 0, " POINTS):"] }), diagnosis.evidence_used && diagnosis.evidence_used.length > 0 ? (_jsx("ul", { className: "space-y-1.5 font-mono text-xs text-zinc-700 dark:text-zinc-300 pl-4 list-disc", children: diagnosis.evidence_used.map((item, idx) => (_jsx("li", { className: "leading-relaxed", children: item }, idx))) })) : (_jsx("div", { className: "text-xs font-mono text-zinc-400 italic", children: "No structured evidence reported." }))] }), diagnosis.reasoning && (_jsxs("div", { className: "pt-2 border-t border-zinc-100 dark:border-zinc-800", children: [_jsx("div", { className: "text-[11px] font-mono font-semibold text-zinc-500 mb-1", children: "STRUCTURED DIAGNOSTIC REASONING:" }), _jsx("div", { className: "p-3 bg-zinc-50 dark:bg-zinc-950 font-mono text-xs text-zinc-800 dark:text-zinc-200 border border-zinc-200 dark:border-zinc-800 leading-relaxed whitespace-pre-wrap", children: diagnosis.reasoning })] }))] })] }), diagnosis.recommended_action && (_jsxs("div", { className: "border border-blue-200 dark:border-blue-900/50 bg-blue-50/40 dark:bg-blue-950/20 p-4 flex items-start gap-3", children: [_jsx("svg", { className: "w-5 h-5 text-blue-600 dark:text-blue-400 shrink-0 mt-0.5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" }) }), _jsxs("div", { children: [_jsx("div", { className: "text-[11px] font-mono font-bold text-blue-700 dark:text-blue-300 uppercase", children: "Recommended Operator Action" }), _jsx("div", { className: "text-xs font-mono text-zinc-800 dark:text-zinc-200 mt-0.5", children: diagnosis.recommended_action })] })] }))] })] }));
};
//# sourceMappingURL=DiagnosticPanel.js.map