import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { useState } from 'react';
export const TechnicalDetails = ({ latestTelemetry, latestDiagnosis, backendStatus, wsEndpoint, }) => {
    const [isOpen, setIsOpen] = useState(false);
    return (_jsxs("div", { "data-testid": "technical-details", className: "border border-zinc-300 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm", children: [_jsxs("button", { onClick: () => setIsOpen(!isOpen), className: "w-full px-4 py-3 flex items-center justify-between text-left hover:bg-zinc-50 dark:hover:bg-zinc-800/50 transition-colors", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "font-mono text-xs font-bold text-zinc-800 dark:text-zinc-200 uppercase tracking-wide", children: "TECHNICAL DIAGNOSTIC TRACE & WIRE PAYLOAD" }), _jsx("span", { className: "text-[10px] font-mono text-zinc-500", children: "[ENGINEERING INSPECTION]" })] }), _jsxs("div", { className: "flex items-center gap-2 text-xs font-mono text-zinc-500", children: [_jsx("span", { children: isOpen ? 'COLLAPSE' : 'EXPAND' }), _jsx("svg", { className: `w-4 h-4 transform transition-transform ${isOpen ? 'rotate-180' : ''}`, fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M19 9l-7 7-7-7" }) })] })] }), isOpen && (_jsxs("div", { className: "p-4 border-t border-zinc-200 dark:border-zinc-800 space-y-4", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("div", { className: "text-[11px] font-mono font-bold text-zinc-500 mb-1", children: "LATEST INGESTED TELEMETRY PACKET (JSON):" }), _jsx("pre", { className: "p-3 bg-zinc-950 text-zinc-300 font-mono text-[11px] overflow-x-auto rounded max-h-60 border border-zinc-800", children: latestTelemetry
                                            ? JSON.stringify(latestTelemetry, null, 2)
                                            : '// No telemetry packet received yet.' })] }), _jsxs("div", { children: [_jsx("div", { className: "text-[11px] font-mono font-bold text-zinc-500 mb-1", children: "LATEST DIAGNOSTIC RESULT PAYLOAD:" }), _jsx("pre", { className: "p-3 bg-zinc-950 text-zinc-300 font-mono text-[11px] overflow-x-auto rounded max-h-60 border border-zinc-800", children: latestDiagnosis
                                            ? JSON.stringify(latestDiagnosis, null, 2)
                                            : '// No diagnosis result recorded yet.' })] })] }), _jsxs("div", { className: "pt-3 border-t border-zinc-200 dark:border-zinc-800 text-xs font-mono text-zinc-600 dark:text-zinc-400 grid grid-cols-1 sm:grid-cols-3 gap-2", children: [_jsxs("div", { children: [_jsx("strong", { children: "Endpoint:" }), " ", wsEndpoint] }), _jsxs("div", { children: [_jsx("strong", { children: "Reasoner Model:" }), " ", backendStatus?.active_model || '—'] }), _jsxs("div", { children: [_jsx("strong", { children: "LLM Reachable:" }), ' ', backendStatus?.llm_reachable ? (_jsx("span", { className: "text-emerald-500 font-bold", children: "YES" })) : (_jsx("span", { className: "text-amber-500 font-bold", children: "NO (FALLBACK ACTIVE)" }))] })] })] }))] }));
};
//# sourceMappingURL=TechnicalDetails.js.map