import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { formatValue, formatTimeAgo } from '../utils/formatters';
export const TelemetryCards = ({ latestTelemetry, highlightMetrics, isAnomaly, }) => {
    const isCurrentHighlighted = highlightMetrics.includes('current_a') && isAnomaly;
    const isRpmHighlighted = highlightMetrics.includes('rpm') && isAnomaly;
    const isDistHighlighted = (highlightMetrics.includes('distance_cm') && isAnomaly) ||
        (latestTelemetry?.distance_plausible === 0);
    const timeAgo = latestTelemetry ? formatTimeAgo(latestTelemetry.timestamp) : 'Waiting for telemetry...';
    return (_jsxs("div", { "data-testid": "telemetry-cards", className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [_jsxs("div", { "data-testid": "telemetry-card-current", className: `border p-4 bg-white dark:bg-zinc-900 shadow-sm transition-colors ${isCurrentHighlighted
                    ? 'border-red-500 bg-red-50/10 dark:bg-red-950/20'
                    : 'border-zinc-300 dark:border-zinc-800'}`, children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("span", { className: "w-2 h-2 rounded-full bg-blue-500" }), _jsx("span", { className: "font-mono text-xs font-bold text-zinc-700 dark:text-zinc-300 uppercase tracking-wide", children: "MOTOR CURRENT" })] }), isCurrentHighlighted && (_jsx("span", { className: "px-1.5 py-0.5 text-[10px] font-mono font-bold bg-red-500/20 text-red-400 border border-red-500/40 rounded animate-pulse", children: "ANOMALOUS" }))] }), _jsxs("div", { className: "flex items-baseline gap-2 my-2", children: [_jsx("span", { className: "font-mono text-3xl font-extrabold text-zinc-900 dark:text-zinc-100", children: formatValue(latestTelemetry?.current_a, 2) }), _jsx("span", { className: "font-mono text-sm font-semibold text-zinc-500", children: "A" })] }), _jsxs("div", { className: "flex items-center justify-between text-[11px] font-mono text-zinc-500 pt-2 border-t border-zinc-100 dark:border-zinc-800", children: [_jsxs("span", { children: ["Freshness: ", timeAgo] }), latestTelemetry?.current_zscore !== undefined && (_jsxs("span", { children: ["Z-Score: ", formatValue(latestTelemetry.current_zscore, 2)] }))] })] }), _jsxs("div", { "data-testid": "telemetry-card-rpm", className: `border p-4 bg-white dark:bg-zinc-900 shadow-sm transition-colors ${isRpmHighlighted
                    ? 'border-red-500 bg-red-50/10 dark:bg-red-950/20'
                    : 'border-zinc-300 dark:border-zinc-800'}`, children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("span", { className: "w-2 h-2 rounded-full bg-emerald-500" }), _jsx("span", { className: "font-mono text-xs font-bold text-zinc-700 dark:text-zinc-300 uppercase tracking-wide", children: "WHEEL RPM" })] }), isRpmHighlighted && (_jsx("span", { className: "px-1.5 py-0.5 text-[10px] font-mono font-bold bg-red-500/20 text-red-400 border border-red-500/40 rounded animate-pulse", children: "ANOMALOUS" }))] }), _jsxs("div", { className: "flex items-baseline gap-2 my-2", children: [_jsx("span", { className: "font-mono text-3xl font-extrabold text-zinc-900 dark:text-zinc-100", children: formatValue(latestTelemetry?.rpm, 1) }), _jsx("span", { className: "font-mono text-sm font-semibold text-zinc-500", children: "RPM" })] }), _jsxs("div", { className: "flex items-center justify-between text-[11px] font-mono text-zinc-500 pt-2 border-t border-zinc-100 dark:border-zinc-800", children: [_jsxs("span", { children: ["Freshness: ", timeAgo] }), latestTelemetry?.rpm_zscore !== undefined && (_jsxs("span", { children: ["Z-Score: ", formatValue(latestTelemetry.rpm_zscore, 2)] }))] })] }), _jsxs("div", { "data-testid": "telemetry-card-distance", className: `border p-4 bg-white dark:bg-zinc-900 shadow-sm transition-colors ${isDistHighlighted
                    ? 'border-amber-500 bg-amber-50/10 dark:bg-amber-950/20'
                    : 'border-zinc-300 dark:border-zinc-800'}`, children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("span", { className: "w-2 h-2 rounded-full bg-purple-500" }), _jsx("span", { className: "font-mono text-xs font-bold text-zinc-700 dark:text-zinc-300 uppercase tracking-wide", children: "ULTRASONIC RANGE" })] }), latestTelemetry?.distance_plausible === 0 ? (_jsx("span", { className: "px-1.5 py-0.5 text-[10px] font-mono font-bold bg-purple-500/20 text-purple-300 border border-purple-500/40 rounded", children: "IMPLAUSIBLE" })) : isDistHighlighted ? (_jsx("span", { className: "px-1.5 py-0.5 text-[10px] font-mono font-bold bg-amber-500/20 text-amber-400 border border-amber-500/40 rounded", children: "FLAGGED" })) : (_jsx("span", { className: "px-1.5 py-0.5 text-[10px] font-mono text-emerald-500", children: "PLAUSIBLE" }))] }), _jsxs("div", { className: "flex items-baseline gap-2 my-2", children: [_jsx("span", { className: "font-mono text-3xl font-extrabold text-zinc-900 dark:text-zinc-100", children: formatValue(latestTelemetry?.distance_cm, 1) }), _jsx("span", { className: "font-mono text-sm font-semibold text-zinc-500", children: "cm" })] }), _jsxs("div", { className: "flex items-center justify-between text-[11px] font-mono text-zinc-500 pt-2 border-t border-zinc-100 dark:border-zinc-800", children: [_jsxs("span", { children: ["Freshness: ", timeAgo] }), _jsx("span", { children: "Sensor: Front Array" })] })] })] }));
};
//# sourceMappingURL=TelemetryCards.js.map